[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "repo-name"
dynamic = ["version"]
description = "XXX"
readme = "README.md"
license-files = ["LICENSE"]
authors = [
    {name = "Zhen Tian", email = "zhen.tian.cs@gmail.com"}
]
requires-python = ""
dependencies = [

]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
]

[project.urls]
Homepage = "https://github.com/user_name/repo-name.git"
Repository = "https://github.com/user_name/repo-name.git"
Issues = "https://github.com/user_name/repo-name.git/issues"

[tool.setuptools.dynamic]
version = {attr = "repo_name.__version__"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["repo_name*"]

[tool.setuptools.package-data]
repo_name = [
    "draw/fonts/*.ttf",
    "draw/fonts/*.TTF"
]
