[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyrelease-cli"
dynamic = ["version"]
description = "A simple CLI tool for building and publishing Python packages."
readme = "README.md"
license-files = ["LICENSE"]
authors = [
    {name = "Zhen Tian", email = "zhen.tian.cs@gmail.com"}
]
requires-python = ">=3.8"

dependencies = [
    "build",
    "twine",
]

[project.scripts]
pyrelease = "pyrelease.cli:main"

[project.urls]
Homepage = "https://github.com/tinchen777/pyrelease-cli.git"
Repository = "https://github.com/tinchen777/pyrelease-cli.git"
Issues = "https://github.com/tinchen777/pyrelease-cli.git/issues"

[tool.setuptools.dynamic]
version = {attr = "pyrelease.__version__"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["pyrelease*"]
